name: piano
description: Utilities and widgets for working with piano sheet music learning.
version: 1.0.4
homepage: https://www.handform.net
repository: https://github.com/craigomac/piano

environment:
  sdk: ">=3.0.0 <3.13.5"
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  equatable: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: 2.4.6
  flutter_test:
    sdk: flutter

flutter:
