name: piano
description: Utilities and widgets for working with piano sheet music learning.
version: 1.0.3+1
homepage: https://www.handform.net
repository: https://github.com/craigomac/piano

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.0.3
  equatable: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  build_runner: 2.1.7
  freezed: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
